/** Same demo data as the original directory page — used to seed MongoDB when empty. */
export const ALUMNI_SEED = [
  {
    name: 'Sarah Johnson',
    photo: '/professional-woman-diverse.png',
    company: 'Google',
    position: 'Senior Software Engineer',
    industry: 'Technology',
    location: 'San Francisco, USA',
    graduationYear: 2015,
  },
  {
    name: 'Michael Chen',
    photo: '/professional-man.jpg',
    company: 'Microsoft',
    position: 'Product Manager',
    industry: 'Technology',
    location: 'Seattle, USA',
    graduationYear: 2014,
  },
  {
    name: 'Emily Rodriguez',
    photo: '/professional-business-woman.png',
    company: 'Amazon',
    position: 'Engineering Manager',
    industry: 'Technology',
    location: 'Seattle, USA',
    graduationYear: 2013,
  },
  {
    name: 'David Kim',
    photo: '/professional-asian-man.png',
    company: 'Apple',
    position: 'Design Lead',
    industry: 'Technology',
    location: 'Cupertino, USA',
    graduationYear: 2016,
  },
  {
    name: 'Jessica Williams',
    photo: '/professional-woman-executive.png',
    company: 'Meta',
    position: 'Data Scientist',
    industry: 'Technology',
    location: 'Menlo Park, USA',
    graduationYear: 2017,
  },
  {
    name: 'Robert Taylor',
    photo: '/professional-man-suit.png',
    company: 'Goldman Sachs',
    position: 'Investment Banker',
    industry: 'Finance',
    location: 'New York, USA',
    graduationYear: 2012,
  },
  {
    name: 'Lisa Anderson',
    photo: '/professional-woman-doctor.png',
    company: 'Johns Hopkins',
    position: 'Medical Researcher',
    industry: 'Healthcare',
    location: 'Baltimore, USA',
    graduationYear: 2011,
  },
  {
    name: 'James Martinez',
    photo: '/professional-man-tech.png',
    company: 'Tesla',
    position: 'Mechanical Engineer',
    industry: 'Technology',
    location: 'Austin, USA',
    graduationYear: 2015,
  },
]
